M48
; DRILL file {KiCad 7.0.1} date Sun Jul 16 00:00:59 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-16T00:00:59-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X8.0711Y-4.1551
X8.2987Y-4.1551
T2
X5.3852Y-4.2624
T3
X-5.93Y-4.48
X-5.35Y-4.45
X3.87Y-1.71
X5.11Y-2.97
X5.26Y-1.09
X6.82Y-1.09
T0
M30
